# Generated by Django 2.0.1 on 2018-02-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('license', models.ImageField(upload_to='')),
                ('isVerified', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('breed', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('isVerified', models.BooleanField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
