# Generated by Django 2.0.1 on 2018-02-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180209_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='age',
        ),
        migrations.AddField(
            model_name='clinic',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='petowner',
            name='registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
