# Generated by Django 2.0.1 on 2018-02-09 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180209_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('remarks', models.TextField(max_length=1024)),
                ('remain_times', models.IntegerField(default=1048576)),
                ('next_time', models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 32, 0, 160327))),
                ('period', models.DateTimeField(default=datetime.timedelta(693))),
                ('type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 2, 9, 15, 32, 0, 161327))),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reminder')),
            ],
        ),
        migrations.AlterField(
            model_name='clinic',
            name='registration_date',
            field=models.DateField(default=datetime.date(2018, 2, 9)),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='registration_date',
            field=models.DateField(default=datetime.date(2018, 2, 9)),
        ),
        migrations.AlterField(
            model_name='vet',
            name='registration_date',
            field=models.DateField(default=datetime.date(2018, 2, 9)),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PetOwner'),
        ),
    ]
