# Generated by Django 2.0.1 on 2018-02-09 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 7, 48, 19, 364334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='singlereminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 7, 48, 19, 365334, tzinfo=utc)),
        ),
    ]
