# Generated by Django 2.0.1 on 2018-02-09 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180209_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 7, 50, 3, 950316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='singlereminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 7, 50, 3, 951316, tzinfo=utc)),
        ),
    ]
