# Generated by Django 2.0.1 on 2018-02-09 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 19, 21, 658851)),
        ),
        migrations.AlterField(
            model_name='singlereminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 19, 21, 659852)),
        ),
    ]
