# Generated by Django 2.0.1 on 2018-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180209_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='next_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='period',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='singlereminder',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vet',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
