# Generated by Django 2.0.1 on 2018-02-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180209_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlereminder',
            name='type',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlereminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PetOwner'),
        ),
    ]
