# Generated by Django 2.0.1 on 2018-02-11 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180210_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('likes', models.ManyToManyField(related_name='likes_likes', to='app.PetOwner')),
                ('reports', models.ManyToManyField(related_name='reports_reports', to='app.PetOwner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PetOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.TextField(max_length=2048)),
                ('likes', models.ManyToManyField(related_name='likes', to='app.PetOwner')),
                ('reports', models.ManyToManyField(related_name='reports', to='app.PetOwner')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PetOwner')),
            ],
        ),
    ]
