# Generated by Django 2.0.1 on 2018-02-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180211_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('clinic_or_vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='app.PhoneNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to='app.PhoneNumber')),
            ],
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_name', to='app.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner_name', to='app.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_name', to='app.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PetOwner'),
        ),
    ]
