# Generated by Django 2.0.1 on 2018-03-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
    ]
