# Generated by Django 2.0.1 on 2018-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180302_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlereminder',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
