# Generated by Django 2.0.1 on 2018-03-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180302_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PhoneNumber')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='abstract',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Clinic'),
        ),
    ]
