# Generated by Django 2.0.1 on 2018-04-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180302_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('breed', models.CharField(max_length=32)),
                ('birthday', models.DateField(null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('weight', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('time', models.DateTimeField()),
                ('type', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClinicRep')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.SmallIntegerField()),
                ('comment', models.TextField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactrecord',
            name='clinic_or_vet',
        ),
        migrations.RemoveField(
            model_name='contactrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='petowner',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='dependency',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='isVerified',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='license',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='password',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='clinic',
            name='geo_hash',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='singlereminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ContactRecord',
        ),
        migrations.DeleteModel(
            name='PetOwner',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.DeleteModel(
            name='Vet',
        ),
        migrations.AddField(
            model_name='rate',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Clinic'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='clinicrep',
            name='clinic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_rep', to='app.Clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'clinic', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('name', 'owner')},
        ),
    ]
