# Generated by Django 2.0.1 on 2018-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180409_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
